### ISSUE TITLE
Sidebars for "Explore API" and "Explore Types" do not load

### ISSUE THREAD

**Issue by joshtransient** [s-KaiNet/sp-rest-explorer#5]
On multiple computers, multiple browsers, app loads but the sidebars are not loading the dynamic content.

HAR attached: [s-kainet.github.io.zip](https://github.com/user-attachments/files/17849599/s-kainet.github.io.zip)

JavaScript console says:
````
sp-rest-explorer/#/:1  Tracking Prevention blocked a Script resource from loading https://www.google-analytics.com/analytics.js.
js?id=UA-134286083-1:98 
        
        
        GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
qc @ js?id=UA-134286083-1:98
XE @ js?id=UA-134286083-1:487
(anonymous) @ js?id=UA-134286083-1:487
hl @ js?id=UA-134286083-1:256
Hl @ js?id=UA-134286083-1:261
YE @ js?id=UA-134286083-1:487
jn @ js?id=UA-134286083-1:277
hn.flush @ js?id=UA-134286083-1:279
hn.push @ js?id=UA-134286083-1:277
config @ js?id=UA-134286083-1:424
Dz @ js?id=UA-134286083-1:433
Fz @ js?id=UA-134286083-1:435
setTimeout
H @ js?id=UA-134286083-1:100
Hz @ js?id=UA-134286083-1:438
(anonymous) @ js?id=UA-134286083-1:571
c @ js?id=UA-134286083-1:564
(anonymous) @ js?id=UA-134286083-1:566
(anonymous) @ js?id=UA-134286083-1:566
(anonymous) @ js?id=UA-134286083-1:578
js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:155 
        
        
        POST https://www.google-analytics.com/g/collect?v=2&tid=G-FMNMXPHNS4&gtm=45je4bk0v9107538364za200&_p=1732208672331&gcd=13l3l3l3l1l1&npa=0&_ng=1&dma=0&tag_exp=101925629~102067555~102067808~102077855~102081485&cid=35501254.1732208673&ul=en-us&sr=3440x1440&ir=1&uaa=x86&uab=64&uafvl=Microsoft%2520Edge%3B131.0.2903.51%7CChromium%3B131.0.6778.70%7CNot_A%2520Brand%3B24.0.0.0&uamb=0&uam=&uap=Windows&uapv=19.0.0&uaw=0&are=1&frm=0&pscdl=noapi&_eu=EAAI&_s=1&sid=1732208672&sct=1&seg=0&dl=https%3A%2F%2Fs-kainet.github.io%2Fsp-rest-explorer%2F&dt=SP%20REST%20API%20Metadata%20Explorer&en=page_view&_fv=1&_nsi=1&_ss=1&tfd=866 net::ERR_BLOCKED_BY_CLIENT
Ec @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:155
uH @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:594
wH.j @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:597
wH.add @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:598
h.ek @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:616
h.gn @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:616
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:613
hl @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:330
Hl @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:335
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:613
c @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:467
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:468
Promise.then
Du @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:468
h.fn @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:613
c @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:628
jn @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:351
hn.flush @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:353
hn.push @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:351
config @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:512
Dz @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:521
Fz @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:523
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:693
c @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:681
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:683
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:683
(anonymous) @ js?id=G-FMNMXPHNS4&l=dataLayer&cx=c&gtm=457e4bk0za200:696
ui.ts:33  Error: Metadata is not loaded yet
    at t.getMetadata (api.ts:31:13)
    at s.metadata (index.ts:32:18)
    at St.get (vue.runtime.esm.js:3029:1)
    at St.evaluate (vue.runtime.esm.js:3136:1)
    at s.metadata (vue.runtime.esm.js:3421:1)
    at s.<anonymous> (vue.runtime.esm.js:455:1)
    at St.get (vue.runtime.esm.js:3029:1)
    at new St (vue.runtime.esm.js:3018:1)
    at e.$watch (vue.runtime.esm.js:3525:1)
    at It (vue.runtime.esm.js:3485:1)
Re @ vue.runtime.esm.js:1683
ze @ vue.runtime.esm.js:1674
Le @ vue.runtime.esm.js:1663
St.get @ vue.runtime.esm.js:3032
St @ vue.runtime.esm.js:3018
e.$watch @ vue.runtime.esm.js:3525
It @ vue.runtime.esm.js:3485
(anonymous) @ vue.runtime.esm.js:3467
Tt @ vue.runtime.esm.js:3238
on._init @ vue.runtime.esm.js:4470
s @ vue.runtime.esm.js:4642
(anonymous) @ vue.runtime.esm.js:4159
init @ vue.runtime.esm.js:3976
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
(anonymous) @ vue.runtime.esm.js:5651
k @ vue.runtime.esm.js:5731
(anonymous) @ vue.runtime.esm.js:5880
e._update @ vue.runtime.esm.js:2568
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St.run @ vue.runtime.esm.js:3106
Ct @ vue.runtime.esm.js:2872
(anonymous) @ vue.runtime.esm.js:1779
We @ vue.runtime.esm.js:1700
Promise.then
Ve @ vue.runtime.esm.js:1748
Ke @ vue.runtime.esm.js:1792
(anonymous) @ vue.runtime.esm.js:2959
St.update @ vue.runtime.esm.js:3096
ae.notify @ vue.runtime.esm.js:673
set @ vue.runtime.esm.js:990
Y.SET_DATA_LOADING @ ui.ts:33
(anonymous) @ vuex.esm.js:697
(anonymous) @ vuex.esm.js:389
(anonymous) @ vuex.esm.js:388
NYxO.c._withCommit @ vuex.esm.js:495
NYxO.c.commit @ vuex.esm.js:387
commit @ vuex.esm.js:335
(anonymous) @ App.vue:46
Promise.then
mounted @ App.vue:45
vt @ vue.runtime.esm.js:2813
insert @ vue.runtime.esm.js:4007
S @ vue.runtime.esm.js:5755
(anonymous) @ vue.runtime.esm.js:5960
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
on._init @ vue.runtime.esm.js:4482
on @ vue.runtime.esm.js:4567
x35b @ main.ts:29
t @ bootstrap 85928b97038bfe93eb17:54
window.webpackJsonp @ bootstrap 85928b97038bfe93eb17:25
(anonymous) @ app.a007f624ea30d4e29c37.js:1
ui.ts:33  Error: Metadata is not loaded yet
    at t.getMetadata (api.ts:31:13)
    at s.metadata (index.ts:32:18)
    at St.get (vue.runtime.esm.js:3029:1)
    at St.evaluate (vue.runtime.esm.js:3136:1)
    at s.metadata (vue.runtime.esm.js:3421:1)
    at s.expandNode (ApiTree.vue:96:48)
    at n (vue.runtime.esm.js:185:1)
    at new e (element-ui.common.js:20695:1)
    at s.created (element-ui.common.js:20603:1)
    at vt (vue.runtime.esm.js:2813:1)
Re @ vue.runtime.esm.js:1683
ze @ vue.runtime.esm.js:1674
Le @ vue.runtime.esm.js:1663
vt @ vue.runtime.esm.js:2815
on._init @ vue.runtime.esm.js:4472
s @ vue.runtime.esm.js:4642
(anonymous) @ vue.runtime.esm.js:4159
init @ vue.runtime.esm.js:3976
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
(anonymous) @ vue.runtime.esm.js:5651
k @ vue.runtime.esm.js:5731
(anonymous) @ vue.runtime.esm.js:5880
e._update @ vue.runtime.esm.js:2568
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St.run @ vue.runtime.esm.js:3106
Ct @ vue.runtime.esm.js:2872
(anonymous) @ vue.runtime.esm.js:1779
We @ vue.runtime.esm.js:1700
Promise.then
Ve @ vue.runtime.esm.js:1748
Ke @ vue.runtime.esm.js:1792
(anonymous) @ vue.runtime.esm.js:2959
St.update @ vue.runtime.esm.js:3096
ae.notify @ vue.runtime.esm.js:673
set @ vue.runtime.esm.js:990
Y.SET_DATA_LOADING @ ui.ts:33
(anonymous) @ vuex.esm.js:697
(anonymous) @ vuex.esm.js:389
(anonymous) @ vuex.esm.js:388
NYxO.c._withCommit @ vuex.esm.js:495
NYxO.c.commit @ vuex.esm.js:387
commit @ vuex.esm.js:335
(anonymous) @ App.vue:46
Promise.then
mounted @ App.vue:45
vt @ vue.runtime.esm.js:2813
insert @ vue.runtime.esm.js:4007
S @ vue.runtime.esm.js:5755
(anonymous) @ vue.runtime.esm.js:5960
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
on._init @ vue.runtime.esm.js:4482
on @ vue.runtime.esm.js:4567
x35b @ main.ts:29
t @ bootstrap 85928b97038bfe93eb17:54
window.webpackJsonp @ bootstrap 85928b97038bfe93eb17:25
(anonymous) @ app.a007f624ea30d4e29c37.js:1
ui.ts:33  TypeError: Cannot read properties of null (reading 'childNodes')
    at s.render (element-ui.common.js:21856:212)
    at e._render (vue.runtime.esm.js:4386:1)
    at s.i (vue.runtime.esm.js:2686:1)
    at St.get (vue.runtime.esm.js:3029:1)
    at new St (vue.runtime.esm.js:3018:1)
    at e (vue.runtime.esm.js:2690:1)
    at on.$mount (vue.runtime.esm.js:7729:1)
    at init (vue.runtime.esm.js:3982:1)
    at vue.runtime.esm.js:5421:1
    at d (vue.runtime.esm.js:5357:1)
Re @ vue.runtime.esm.js:1683
ze @ vue.runtime.esm.js:1674
Le @ vue.runtime.esm.js:1663
e._render @ vue.runtime.esm.js:4388
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
m @ vue.runtime.esm.js:5492
d @ vue.runtime.esm.js:5397
(anonymous) @ vue.runtime.esm.js:5875
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
init @ vue.runtime.esm.js:3982
(anonymous) @ vue.runtime.esm.js:5421
d @ vue.runtime.esm.js:5357
(anonymous) @ vue.runtime.esm.js:5651
k @ vue.runtime.esm.js:5731
(anonymous) @ vue.runtime.esm.js:5880
e._update @ vue.runtime.esm.js:2568
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St.run @ vue.runtime.esm.js:3106
Ct @ vue.runtime.esm.js:2872
(anonymous) @ vue.runtime.esm.js:1779
We @ vue.runtime.esm.js:1700
Promise.then
Ve @ vue.runtime.esm.js:1748
Ke @ vue.runtime.esm.js:1792
(anonymous) @ vue.runtime.esm.js:2959
St.update @ vue.runtime.esm.js:3096
ae.notify @ vue.runtime.esm.js:673
set @ vue.runtime.esm.js:990
Y.SET_DATA_LOADING @ ui.ts:33
(anonymous) @ vuex.esm.js:697
(anonymous) @ vuex.esm.js:389
(anonymous) @ vuex.esm.js:388
NYxO.c._withCommit @ vuex.esm.js:495
NYxO.c.commit @ vuex.esm.js:387
commit @ vuex.esm.js:335
(anonymous) @ App.vue:46
Promise.then
mounted @ App.vue:45
vt @ vue.runtime.esm.js:2813
insert @ vue.runtime.esm.js:4007
S @ vue.runtime.esm.js:5755
(anonymous) @ vue.runtime.esm.js:5960
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
on._init @ vue.runtime.esm.js:4482
on @ vue.runtime.esm.js:4567
x35b @ main.ts:29
t @ bootstrap 85928b97038bfe93eb17:54
window.webpackJsonp @ bootstrap 85928b97038bfe93eb17:25
(anonymous) @ app.a007f624ea30d4e29c37.js:1
ui.ts:33  TypeError: this.$el.querySelectorAll is not a function
    at s.initTabindex (element-ui.common.js:20559:1)
    at s.n [as initTabindex] (vue.runtime.esm.js:187:1)
    at s.mounted (element-ui.common.js:20622:1)
    at vt (vue.runtime.esm.js:2813:1)
    at Object.insert (vue.runtime.esm.js:4007:1)
    at S (vue.runtime.esm.js:5755:1)
    at s.__patch__ (vue.runtime.esm.js:5960:1)
    at e._update (vue.runtime.esm.js:2568:1)
    at s.i (vue.runtime.esm.js:2686:1)
    at St.get (vue.runtime.esm.js:3029:1)
Re @ vue.runtime.esm.js:1683
ze @ vue.runtime.esm.js:1674
Le @ vue.runtime.esm.js:1663
vt @ vue.runtime.esm.js:2815
insert @ vue.runtime.esm.js:4007
S @ vue.runtime.esm.js:5755
(anonymous) @ vue.runtime.esm.js:5960
e._update @ vue.runtime.esm.js:2568
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St.run @ vue.runtime.esm.js:3106
Ct @ vue.runtime.esm.js:2872
(anonymous) @ vue.runtime.esm.js:1779
We @ vue.runtime.esm.js:1700
Promise.then
Ve @ vue.runtime.esm.js:1748
Ke @ vue.runtime.esm.js:1792
(anonymous) @ vue.runtime.esm.js:2959
St.update @ vue.runtime.esm.js:3096
ae.notify @ vue.runtime.esm.js:673
set @ vue.runtime.esm.js:990
Y.SET_DATA_LOADING @ ui.ts:33
(anonymous) @ vuex.esm.js:697
(anonymous) @ vuex.esm.js:389
(anonymous) @ vuex.esm.js:388
NYxO.c._withCommit @ vuex.esm.js:495
NYxO.c.commit @ vuex.esm.js:387
commit @ vuex.esm.js:335
(anonymous) @ App.vue:46
Promise.then
mounted @ App.vue:45
vt @ vue.runtime.esm.js:2813
insert @ vue.runtime.esm.js:4007
S @ vue.runtime.esm.js:5755
(anonymous) @ vue.runtime.esm.js:5960
e._update @ vue.runtime.esm.js:2558
i @ vue.runtime.esm.js:2686
St.get @ vue.runtime.esm.js:3029
St @ vue.runtime.esm.js:3018
e @ vue.runtime.esm.js:2690
on.$mount @ vue.runtime.esm.js:7729
on._init @ vue.runtime.esm.js:4482
on @ vue.runtime.esm.js:4567
x35b @ main.ts:29
t @ bootstrap 85928b97038bfe93eb17:54
window.webpackJsonp @ bootstrap 85928b97038bfe93eb17:25
(anonymous) @ app.a007f624ea30d4e29c37.js:1
````

**Comment by influential-eliot** [comment]
Yeah, I noticed this, too ... was just coming here to mention that.
 
Point of fact, the non-dynamic content doesn't load, either.
 
It's just blank, before or after filtering.

Have also tried to check one of the new boxes in the 'Filter settings' ... but it did nothing to change things.

**Comment by influential-eliot** [comment]
Loving your work, matey ... would you mind if I got in touch privately?
 
I'd like to build automations that are reactive to API changes/advances, and am curious about your process, here. :)

**Comment by s-KaiNet** [comment]
> Loving your work, matey ... would you mind if I got in touch privately?
> 
> I'd like to build automations that are reactive to API changes/advances, and am curious about your process, here. :)

Thank you! Sure, you can find my email in the GH profile.
